[[GStreamer]]
arch = "aarch64"
git-tree-sha1 = "517f783b9258d48205353540ceafbadc819bd20f"
os = "macos"

    [[GStreamer.download]]
    sha256 = "3b7e42952be4dafc6c56fe3763a561064324c0c831445fe086af7433e56b71ea"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.aarch64-apple-darwin.tar.gz"
[[GStreamer]]
arch = "aarch64"
git-tree-sha1 = "adf83eb9ff480589fec8f51204d64af678dc6272"
libc = "glibc"
os = "linux"

    [[GStreamer.download]]
    sha256 = "752d70a6e146c70685c6851ea8a8c5d8d96d73d7bf8439ea2bea98cf05f118b7"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.aarch64-linux-gnu.tar.gz"
[[GStreamer]]
arch = "aarch64"
git-tree-sha1 = "5defeb81035ab08340684c75474df1b94e773395"
libc = "musl"
os = "linux"

    [[GStreamer.download]]
    sha256 = "1b09045b93a17f1454a86b4c4398bfd2d5db1896a15be93d0d22d8fea78dfd0c"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.aarch64-linux-musl.tar.gz"
[[GStreamer]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "411c477c9edd9db01599f9be901ae30e86f40389"
libc = "glibc"
os = "linux"

    [[GStreamer.download]]
    sha256 = "1772cc7ade2df5fada0f91d611fbefce77bc1ff14bd56d441e362bdd8276d28e"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.armv6l-linux-gnueabihf.tar.gz"
[[GStreamer]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dc99a80ef69a7ac824a1dbe5c1f5d66fb1d1e473"
libc = "musl"
os = "linux"

    [[GStreamer.download]]
    sha256 = "d665f3f440e7a33ca3d6ef7f33a4f575442423b7c1a5b759c1f686f62a52ff80"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.armv6l-linux-musleabihf.tar.gz"
[[GStreamer]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d647761c57e25d3c9456f7ac77efba8e9db463f5"
libc = "glibc"
os = "linux"

    [[GStreamer.download]]
    sha256 = "e5758649f5dfa24207ec7ebdcf9b784e54c69b58ae2197f387e34df2e4c31800"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.armv7l-linux-gnueabihf.tar.gz"
[[GStreamer]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "58cc869af4465b27b9c40c8299e3f994df9fb5e1"
libc = "musl"
os = "linux"

    [[GStreamer.download]]
    sha256 = "5ada1809091011de94b94490ed2fc656d1435417ff496a2e23991020a4f2daef"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.armv7l-linux-musleabihf.tar.gz"
[[GStreamer]]
arch = "i686"
git-tree-sha1 = "a7140d87c576987008e6ad3e3abfaeeb76ed9d0f"
libc = "glibc"
os = "linux"

    [[GStreamer.download]]
    sha256 = "410d2bde5a8040a06fb19c3dd91955bd57aaa34b810cb1de9d7629c6fdbb5a9c"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.i686-linux-gnu.tar.gz"
[[GStreamer]]
arch = "i686"
git-tree-sha1 = "f77cfd6d784bdfe8eb6ab57b72088bedfd5253c3"
os = "windows"

    [[GStreamer.download]]
    sha256 = "92a429369f9459b429265d45a69219df5a7a4a8a73f5690453c503ea45ddf04e"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.i686-w64-mingw32.tar.gz"
[[GStreamer]]
arch = "x86_64"
git-tree-sha1 = "1e1846fb6fa56373d63abeb055f471af894eca52"
os = "macos"

    [[GStreamer.download]]
    sha256 = "b1c7d7cf122da2f7506f9934a7ddf26496f1b99b10ff31871286f3a41aa6339f"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.x86_64-apple-darwin.tar.gz"
[[GStreamer]]
arch = "x86_64"
git-tree-sha1 = "bbebdc05c461d73b9d28ef5e61d3d111dc84ed43"
libc = "glibc"
os = "linux"

    [[GStreamer.download]]
    sha256 = "5159e009821dd6f91e9e0abc62d462711fdff052c521de29cf6ed635f184fcc3"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.x86_64-linux-gnu.tar.gz"
[[GStreamer]]
arch = "x86_64"
git-tree-sha1 = "b4388e73d0b62e75a5e6ad568f93e9b7ef701bef"
libc = "musl"
os = "linux"

    [[GStreamer.download]]
    sha256 = "430055b3f28239d9b5ec66123e787009237689d7e45ce97915578a761a4cd22e"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.x86_64-linux-musl.tar.gz"
[[GStreamer]]
arch = "x86_64"
git-tree-sha1 = "447be02abb4c20609d99902aee0abec46ded6330"
os = "freebsd"

    [[GStreamer.download]]
    sha256 = "2fa19eb67dbd506c34e097bcbe701de28617703e6f030cb78266e1b993f26392"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.x86_64-unknown-freebsd.tar.gz"
[[GStreamer]]
arch = "x86_64"
git-tree-sha1 = "cda5c4c04a16694b17c2a9fabbcbaccdf36439ec"
os = "windows"

    [[GStreamer.download]]
    sha256 = "6aa1447b47bbfde44f06ff701907e9af352c3af20de2bf76d2134b9f4d8c9aa0"
    url = "https://github.com/JuliaBinaryWrappers/GStreamer_jll.jl/releases/download/GStreamer-v1.20.3+0/GStreamer.v1.20.3.x86_64-w64-mingw32.tar.gz"
